filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/nginx/access.log

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.kibana:
  host: "http://kibana:5601"
setup.dashboards.enabled: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]